name: Status Check

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl https://www.turkosaur.us

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
