name: Status Check

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: curl https://www.turkosaur.us

      # Runs a set of commands using the runners shell
      - name: Check and record website status and ISO-3166 timestamp
        run: |
          sites=('https://www.turkosaur.us' 'https://www.google.com')
          for site in ${sites[*]}
          do
            echo $(date +"%Y-%m-%dT%H:%M:%S%:z")',' $site',' $(curl -LIs $site -o /dev/null -w '%{http_code}')
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Capture status check results
