name: Status Check

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-sites:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Check website status and save with ISO-3166 timestamp to status.csv
        run: |
          sites=(
            'https://www.turkosaur.us'
             'https://nailivic.herokuapp.com/login'
          )
          for site in ${sites[*]}
          do
            echo $(date +"%Y-%m-%dT%H:%M:%S%:z")',' $site',' $(curl -LIs $site -o /dev/null -w '%{http_code}') >> status.csv
          done
          cat status.csv
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Capture status check results
